services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: nexus_db
      POSTGRES_USER: nexus_user
      POSTGRES_PASSWORD: nexus_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - nexus-network

  # Python Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://nexus_user:nexus_password@postgres:5432/nexus_db
      JWT_SECRET: nexus_jwt_secret_key_2024
      CORS_ORIGINS: http://localhost:4000,http://frontend:3000
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - nexus-network

  # Next.js Frontend
  frontend:
    build:
      context: ./nexus-app
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api
    depends_on:
      - backend
    volumes:
      - ./nexus-app:/app
      - /app/node_modules
      - /app/.next
    networks:
      - nexus-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "4000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - nexus-network

volumes:
  postgres_data:

networks:
  nexus-network:
    driver: bridge