
services:
  postgres:
    image: postgres:15-alpine
    container_name: nexus_postgres
    environment:
      POSTGRES_DB: nexus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "3001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-db:/docker-entrypoint-initdb.d
    networks:
      - nexus_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nexus_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/nexus
      SECRET_KEY: your-secret-key-change-in-production
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: your-email@gmail.com
      SMTP_PASSWORD: your-app-password
    ports:
      - "3002:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - nexus_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nexus_frontend
    ports:
      - "3003:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3002
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - nexus_network

  nginx:
    image: nginx:alpine
    container_name: nexus_nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - nexus_network

networks:
  nexus_network:
    driver: bridge

volumes:
  postgres_data: